support for differently named identifier columns
Qbox-project/qbx-core pull request #128
Opened 2023-09-13 06:39 UTC by hakanesnn

## Description

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ ] My code fits the style guidelines.
- [ ] My PR fits the contribution guidelines.

2023-09-13 06:52 UTC, Manason commented
I'm not sure the database schema should be something open to be dynamically configured. Why are you desiring to rename the id column?

2023-09-13 07:05 UTC, Manason commented
> When I install with qbox txadminrecipe, renewed-banking is installed, renewed-banking creates the created accounts to the db with the creator column, not the citizenid column, I think that when the character is deleted, the accounts belonging to the character should also be deleted. this is just an example of renewed-banking, other script creators may not save the data to a column named citizenid when saving to the db, I needed something like this because the characters are now managed from within qbx-core.

Could we solve this problem by triggering an event when player is deleted and then you could clean up non qbx tables by consuming that event?

2023-09-13 08:30 UTC, FjamZoo commented on server/storage.lua
> +    local query = "DELETE FROM %s WHERE %s = ?"
```suggestion
    local query = 'DELETE FROM %s WHERE %s = ?'
```

pretty please thank you

2023-09-13 08:31 UTC, FjamZoo commented
> Could we solve this problem by triggering an event when player is deleted and then you could clean up non qbx tables by consuming that event?

or imagine this we could use something thats called foreign keys 🤯

2023-09-13 14:46 UTC, Manason requested changes

2023-09-13 14:46 UTC, Manason commented on config.lua
> +}
Could we put this in a new Config object? I'm not sure there is a reason to expose this table data outside of the core.

Also consider putting a comment that these are the rows that will be deleted when a character is deleted.

Also consider renaming to CharacterDataTables. Using character as much as possible will open us up to one day separating the concept of a player

2023-09-13 14:47 UTC, Manason commented
> Yes it solves but I don't think it will be user friendly. As I understand you don't want to write non qbx tables into qbx-core, you can do it by leaving only qbx tables in the cfg I sent. Users who want to add other tables can configure the config file.

Ok. I think I'm convinced since we do want everything in one transaction. See my requested changes, but I'm willing to approve the concept of this PR.

2023-09-14 00:54 UTC, Manason requested changes

2023-09-14 00:54 UTC, Manason commented on config.lua
> +CharacterDataTables = {
Config = {}
Config.CharacterDataTables = ...

I like having the Config object to signify that this isn't supposed to be a mutable global variable, but rather an immutable field set in config

2023-09-14 06:06 UTC, Manason approved these changes

2023-09-15 16:41 UTC, merged